### ISSUE TITLE
Question: Custom scroll container?

### ISSUE THREAD

**Issue by schnubor** [Purii/react-use-scrollspy#385]
Hi,

thanks for this hook. I was wondering if it would be possible to use it with a custom scroll container, e.g. a fixed height div with `overflow: auto` containing my list of sections. If so a quick example would be appreciated. 

Cheers

**Comment by Purii** [comment]
Hi!

For that I would suggest to fork or just copy the code of the hook and adapt it to your requirements.
Currently there's an event hander listening for onScroll events on `window`. In order to make this work with a custom scroll container you need to listen to the onScroll events emitted by that element.

https://github.com/Purii/react-use-scrollspy/blob/3729b2277d4f739a0783a83a3420b246cc2c5fe2/src/index.ts#L37

Patrick

**Comment by schnubor** [comment]
Thanks, that answers the question :) closing

**Comment by srmelody** [comment]
If you're seeing this issue in the future, please know that you can use pass a `scrollingElement`. You do not need to fork or copy the hook's code into your own codebase.
